import type {
  TaskType,
  BudgetRange,
  Urgency,
  AcceptorType,
  TaskStatus,
} from "./types.js";

/**
 * Parse a GitHub issue body generated by the task-request.yml template.
 * The template produces sections delimited by `### Heading`.
 */
export function parseIssueBody(body: string): {
  type: TaskType | null;
  budget: BudgetRange | null;
  urgency: Urgency | null;
  description: string;
  deliverables: string;
  requirements: string | null;
  acceptorType: AcceptorType | null;
  contact: string | null;
} {
  const sections = parseSections(body);

  return {
    type: parseTaskType(sections["Task Type"]),
    budget: parseBudget(sections["Budget Range"]),
    urgency: parseUrgency(sections["Urgency"]),
    description: sections["Task Description"] || "",
    deliverables: sections["Expected Deliverables"] || "",
    requirements: sections["Requirements & Constraints"] || null,
    acceptorType: parseAcceptorType(sections["Who can accept this?"]),
    contact: sections["Payment Type"] || sections["Payment/Contact Method"] || null,
  };
}

/**
 * Build an issue body matching the task-request.yml template format.
 */
export function buildIssueBody(fields: {
  type: string;
  budget: string;
  urgency: string;
  description: string;
  deliverables: string;
  requirements?: string;
  acceptorType?: string;
  contact?: string;
}): string {
  const lines = [
    `### Task Type\n\n${fields.type}`,
    `### Budget Range\n\n${fields.budget}`,
    `### Urgency\n\n${fields.urgency}`,
    `### Task Description\n\n${fields.description}`,
    `### Expected Deliverables\n\n${fields.deliverables}`,
  ];

  if (fields.requirements) {
    lines.push(`### Requirements & Constraints\n\n${fields.requirements}`);
  } else {
    lines.push(`### Requirements & Constraints\n\n_No response_`);
  }

  lines.push(`### Who can accept this?\n\n${fields.acceptorType || "Anyone (human or AI)"}`);

  lines.push(`### Payment Type\n\n${fields.contact || "Paid (details exchanged privately after acceptance)"}`);

  return lines.join("\n\n");
}

/**
 * Extract task status from issue labels.
 */
export function extractStatus(labels: Array<{ name: string }>): TaskStatus {
  for (const label of labels) {
    if (label.name.startsWith("status:")) {
      return label.name.replace("status:", "") as TaskStatus;
    }
  }
  return "open";
}

/**
 * Extract worker username from issue comments (look for the Gofer Bot claim message).
 */
export function extractWorkerFromComments(
  comments: Array<{ body?: string | null }>
): string | null {
  for (const comment of comments) {
    const match = comment.body?.match(/\*\*\[Gofer Bot\]\*\* @(\S+) has claimed this task/);
    if (match) return match[1];
  }
  return null;
}

// --- Internal helpers ---

function parseSections(body: string): Record<string, string> {
  const sections: Record<string, string> = {};
  const parts = body.split(/^### /m);

  for (const part of parts) {
    if (!part.trim()) continue;
    const newlineIdx = part.indexOf("\n");
    if (newlineIdx === -1) continue;
    const heading = part.substring(0, newlineIdx).trim();
    const content = part.substring(newlineIdx + 1).trim();
    if (content !== "_No response_") {
      sections[heading] = content;
    }
  }

  return sections;
}

function parseTaskType(value: string | undefined): TaskType | null {
  if (!value) return null;
  const v = value.toLowerCase().trim();
  const valid: TaskType[] = ["research", "code", "writing", "design", "automation", "data-analysis", "web-scraping", "translation", "video", "audio", "seo", "testing", "data-entry", "api-integration", "chatbot", "social-media", "game-dev", "subscription", "other"];
  return valid.includes(v as TaskType) ? (v as TaskType) : null;
}

function parseBudget(value: string | undefined): BudgetRange | null {
  if (!value) return null;
  const map: Record<string, BudgetRange> = {
    "$0 (volunteer/open-source)": "free",
    "$1-$25": "low",
    "$25-$100": "mid",
    "$100-$500": "high",
    "$500+": "premium",
    "negotiable": "negotiable",
  };
  return map[value.trim()] || null;
}

function parseUrgency(value: string | undefined): Urgency | null {
  if (!value) return null;
  const map: Record<string, Urgency> = {
    "No rush (1+ week)": "low",
    "Normal (2-5 days)": "normal",
    "Urgent (24-48 hours)": "urgent",
    "ASAP (< 24 hours)": "asap",
  };
  return map[value.trim()] || null;
}

function parseAcceptorType(value: string | undefined): AcceptorType | null {
  if (!value) return null;
  const map: Record<string, AcceptorType> = {
    "Anyone (human or AI)": "anyone",
    "Humans only": "human-only",
    "AI agents only": "ai-only",
  };
  return map[value.trim()] || null;
}
